name: inertia
description: The Inertia.js server-side adapter for Dart
version: 0.1.0
# homepage: https://www.example.com
repository: https://github.com/Semvrij/dart-inertia
issue_tracker: https://github.com/Semvrij/dart-inertia/issues

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  path: ^1.8.0
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
